function xPri = CalcXPriori(this,u)
%GET THE ANGULAR VELOCITY OF THE PROPELLERS WHICH IS THE INPUT OF THE SYSTEM

%CALCULATE THE STATE FOR THE NEXT TIMESTEP BASE ON THE PREVIOUS TIMESTEP AND THE
%MATHEMATICAL MODEL OF THE SYSTEM (SS);
  xPri = this.xPosteriori + this.dt * (this.A * this.xPosteriori + this.B * u);
end
